-- Update information in the database.

-- Set Cleo Goldwater's favorite dish to
-- the Quinoa Salmon Salad.

SELECT *
FROM CUSTOMERS
WHERE UPPER(FIRSTNAME) = 'CLEO';

UPDATE Customers
SET FAVORITEDISH = (SELECT DISHID FROM DISHES WHERE UPPER(NAME) = 'QUINOA SALMON SALAD')
WHERE CUSTOMERID = 42;

SELECT *
FROM CUSTOMERS
WHERE UPPER(FIRSTNAME) = 'CLEO' 